name: check

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    -   cron: '0 3 * * *'

# Allow cancelling all previous runs for the same branch
# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Build plugin
        uses: gradle/actions/setup-gradle@v4
        with:
          arguments: ":buildPlugin -Pversion=SNAPSHOT-${{ github.run_number }}"

      - name: Upload plugin archive
        uses: actions/upload-artifact@v4
        with:
          name: intellij-micropython-SNAPSHOT-${{ github.run_number }}
          path: build/distributions/intellij-micropython-SNAPSHOT-${{ github.run_number }}.zip
